### ISSUE TITLE
smart EDCのソフトウェアの最新版をGitHubにアップする

### ISSUE THREAD

**Issue by somacells** [epoc-software-open/SEDC#1]
タイミングを相談させてください。

**Comment by osws-makino** [comment]
失礼します。
このメッセージが永原さんにしか届いていない可能性があります。（私には届かなかった）
横の「Assignees」に担当して欲しい方を入れておくと、issueが書かれたらその方へとメッセージが飛ぶようになります。

**Comment by somacells** [comment]
@osws-makino さん、ありがとうございます。プロジェクトからissueを作成するとassignessが指定できないみたいです。
いろいろ使っているとわかることもありますね。。

**Comment by osws-makino** [comment]
あ！　そうなんだ。それは知らなかったです。プロジェクトからのissue提起ではダメなんですね。
１つ賢くなりました。

**Comment by somacells** [comment]
プロジェクトから登録する方が多いような気もするんですけどね。。ありがとうございます。

**Comment by osws-makino** [comment]
（なるほど。私はいつもissueは「issue」から登録する事が癖づいてしまっていたので）

**Comment by somacells** [comment]
そうなんですね、承知しました。またよろしくお願いいたします。

**Comment by somacells** [comment]
V3アップしました。
